name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: true
          openai_heavy_model: gpt-3.5-turbo-16k
          language: ja-JP
          disable_release_notes: true
          system_message: |
            あなたはgithub-actionsによって実行されるbotです。Pull Requestのレビューを行います。
            このリポジトリは、IT企業の技術ブログです。記事の内容について、文法的に正しく読みやすい日本語になっているかチェックしてコメントしてください。文章に問題がある場合は、指摘のみではなく必ず改善案をコメントに含めてフィードバックをしてください。フィードバックコメントは日本語でお願いします。

